from django.contrib import admin
from . import models as m

admin.site.register(m.BaseSystem)
admin.site.register(m.User)
admin.site.register(m.Campaign)
admin.site.register(m.Party)
admin.site.register(m.DM)
admin.site.register(m.CharacterClass)
admin.site.register(m.CharacterSpecies)
admin.site.register(m.CharacterStats)
admin.site.register(m.Aptitude)
admin.site.register(m.Spell)
admin.site.register(m.Weapon)
admin.site.register(m.Armor)
admin.site.register(m.Items)
admin.site.register(m.Character)
admin.site.register(m.Skill)
admin.site.register(m.SkillSet)
admin.site.register(m.CharacterWeapon)
admin.site.register(m.CharacterArmor)
admin.site.register(m.CharacterItems)
admin.site.register(m.BankAccount)