# Generated by Django 4.2.7 on 2023-11-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='party',
            field=models.CharField(max_length=200),
        ),
    ]
