# Generated by Django 4.2.7 on 2023-11-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_guidmodel_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidmodel',
            name='guid',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
