# Generated by Django 4.2.7 on 2023-11-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_guidmodel_guid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidmodel',
            old_name='guid',
            new_name='id',
        ),
    ]
