# Generated by Django 4.2.7 on 2023-11-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_guid_guidmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('campaign_name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=5000)),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='party',
            new_name='party_list',
        ),
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='character',
            name='diplomacy',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('party_name', models.CharField(default='', max_length=100)),
                ('quadgram', models.CharField(default='', max_length=4)),
                ('party_character', models.CharField(default='', max_length=200)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.campaign')),
            ],
            bases=('webapp.guidmodel',),
        ),
    ]
