# Generated by Django 4.2.7 on 2023-11-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_party_character_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='quadgram',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pseudo',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
