# Generated by Django 4.2.7 on 2023-12-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_campaign_campaign_name_alter_party_quadgram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DM',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.party')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user')),
            ],
            bases=('webapp.guidmodel',),
        ),
    ]
