# Generated by Django 4.2.7 on 2023-12-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_dm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='quadgram',
        ),
        migrations.AddField(
            model_name='campaign',
            name='quadgram',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
    ]
