# Generated by Django 4.2.7 on 2023-12-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_party_quadgram_campaign_quadgram'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSystem',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('system_name', models.CharField(default='', max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=5000, null=True)),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.CreateModel(
            name='Character_Race',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('race_name', models.CharField(default='', max_length=200)),
                ('is_homebrew', models.BooleanField(default=False)),
                ('strength', models.IntegerField(default=0)),
                ('agility', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('diplomacy', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('base_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.basesystem')),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.CreateModel(
            name='Character_Class',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('class_name', models.CharField(default='Commoner', max_length=200)),
                ('is_homebrew', models.BooleanField(default=False)),
                ('strength', models.IntegerField(default=0)),
                ('agility', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('diplomacy', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('base_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.basesystem')),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.AddField(
            model_name='campaign',
            name='base_system_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.basesystem'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.character_class'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_race_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.character_race'),
        ),
    ]
