# Generated by Django 4.2.7 on 2024-02-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_basesystem_character_race_character_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('is_from_class', models.BooleanField(default=False)),
                ('is_from_race', models.BooleanField(default=True)),
                ('aptitude_name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=5000)),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('armor_name', models.CharField(default='', max_length=200)),
                ('ca', models.IntegerField(default=11)),
                ('max_dex_modifier', models.IntegerField(default=2)),
                ('required_force', models.IntegerField(default=0)),
                ('disadvantage_discretion', models.BooleanField(default=False)),
                ('disadvantage_athletism', models.BooleanField(default=False)),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('weapon_name', models.CharField(default='', max_length=200)),
                ('damages', models.IntegerField(default=4)),
                ('damage_type', models.CharField(blank=True, default='', max_length=100)),
                ('properties', models.CharField(blank=True, default='', max_length=500)),
                ('ammo', models.IntegerField(blank=True, default=0)),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.AddField(
            model_name='character_class',
            name='hp_dice',
            field=models.IntegerField(default=6),
        ),
        migrations.CreateModel(
            name='characterWeapon',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('is_equipped', models.BooleanField(default=False)),
                ('ammo_count', models.IntegerField(blank=True, default=0)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.character')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.weapon')),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.CreateModel(
            name='characterArmor',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('is_equipped', models.BooleanField(default=False)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.character')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.armor')),
            ],
            bases=('webapp.guidmodel',),
        ),
    ]
