# Generated by Django 4.2.7 on 2024-02-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_aptitude_armor_weapon_character_class_hp_dice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='agility',
            new_name='dexterity',
        ),
        migrations.RenameField(
            model_name='character_class',
            old_name='agility',
            new_name='dexterity',
        ),
        migrations.RenameField(
            model_name='character_race',
            old_name='agility',
            new_name='dexterity',
        ),
        migrations.AddField(
            model_name='aptitude',
            name='is_homebrew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='aptitude',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='character',
            name='diplomacy',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='items',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
