# Generated by Django 4.2.7 on 2024-02-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_rename_agility_character_dexterity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character_Class',
            new_name='CharacterClass',
        ),
        migrations.RenameModel(
            old_name='Character_Race',
            new_name='CharacterRace',
        ),
    ]
