# Generated by Django 4.2.7 on 2024-02-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_rename_character_class_characterclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='constitution',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='constitution',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='diplomacy',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='diplomacy',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
