# Generated by Django 4.2.7 on 2024-02-24 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_characterclass_constitution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('spell_name', models.CharField(default='', max_length=200)),
                ('damages', models.IntegerField(default=0, null=True)),
                ('level', models.IntegerField(blank=True, default=0)),
                ('property', models.CharField(blank=True, default='', max_length=500)),
                ('is_bonus_action', models.BooleanField(default=False)),
                ('is_homebrew', models.BooleanField(default=False)),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.RenameField(
            model_name='armor',
            old_name='disadvantage_discretion',
            new_name='disadvantage_stealth',
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='hp_dice',
            field=models.IntegerField(default=6, null=True),
        ),
    ]
