# Generated by Django 4.2.7 on 2024-03-02 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_spell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('item_name', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('is_homebrew', models.BooleanField(default=False)),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.RemoveField(
            model_name='character',
            name='items',
        ),
        migrations.AddField(
            model_name='armor',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='armor',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='copper_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='gold_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='platinum_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='proficiency_bonus',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='character',
            name='silver_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CharacterItems',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('is_item_hidden', models.BooleanField(default=False)),
                ('character_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.character')),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.items')),
            ],
            bases=('webapp.guidmodel',),
        ),
    ]
