# Generated by Django 4.2.7 on 2024-11-09 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_items_remove_character_items_armor_is_damaged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('skill_name', models.CharField(default='', max_length=50)),
                ('is_expertise', models.BooleanField(default=False)),
                ('is_saving_throw', models.BooleanField(default=False)),
                ('base_system_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.basesystem')),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.character')),
            ],
            bases=('webapp.guidmodel',),
        ),
    ]
