# Generated by Django 4.2.7 on 2024-11-10 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='base_system_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.basesystem'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='character_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.character'),
        ),
    ]
