# Generated by Django 4.2.7 on 2024-11-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_skills_base_system_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('strength', models.IntegerField(default=10, null=True)),
                ('str_mod', models.IntegerField(default=0, null=True)),
                ('dexterity', models.IntegerField(default=10, null=True)),
                ('dex_mod', models.IntegerField(default=0, null=True)),
                ('constitution', models.IntegerField(default=10, null=True)),
                ('con_mod', models.IntegerField(default=0, null=True)),
                ('intelligence', models.IntegerField(default=10, null=True)),
                ('int_mod', models.IntegerField(default=0, null=True)),
                ('wisdom', models.IntegerField(default=10, null=True)),
                ('wis_mod', models.IntegerField(default=0, null=True)),
                ('charisma', models.IntegerField(default=10, null=True)),
                ('cha_mod', models.IntegerField(default=0, null=True)),
                ('diplomacy', models.IntegerField(default=None, null=True)),
                ('dip_mod', models.IntegerField(default=None, null=True)),
                ('physic', models.IntegerField(default=None, null=True)),
                ('social', models.IntegerField(default=None, null=True)),
                ('mental', models.IntegerField(default=None, null=True)),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.RenameModel(
            old_name='CharacterRace',
            new_name='CharacterSpecies',
        ),
        migrations.RenameField(
            model_name='aptitude',
            old_name='is_from_race',
            new_name='is_from_species',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_race_id',
            new_name='character_species_id',
        ),
        migrations.RenameField(
            model_name='characterspecies',
            old_name='race_name',
            new_name='species_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='character',
            name='diplomacy',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wisdom',
        ),
        migrations.AddField(
            model_name='character',
            name='character_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.characterstats'),
        ),
    ]
