# Generated by Django 4.2.7 on 2024-11-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_characterstats_rename_characterrace_characterspecies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('skill_name', models.CharField(default='', max_length=50)),
                ('is_saving_throw', models.BooleanField(default=False)),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('skill_set_name', models.CharField(default='', max_length=200)),
                ('skill_list', models.CharField(default='', max_length=640)),
                ('base_system_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.basesystem')),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.AddField(
            model_name='spell',
            name='class_limit',
            field=models.CharField(blank=True, default='', max_length=320, null=True),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
