# Generated by Django 4.2.7 on 2024-11-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_skill_skillset_spell_class_limit_delete_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterstats',
            name='dip_mod',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='characterstats',
            name='diplomacy',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='characterstats',
            name='mental',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='characterstats',
            name='physic',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='characterstats',
            name='social',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
