# Generated by Django 4.2.7 on 2024-11-17 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_characterstats_dip_mod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='diplomacy',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='wisdom',
        ),
        migrations.RemoveField(
            model_name='characterspecies',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='characterspecies',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='characterspecies',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='characterspecies',
            name='diplomacy',
        ),
        migrations.RemoveField(
            model_name='characterspecies',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='characterspecies',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='characterspecies',
            name='wisdom',
        ),
        migrations.AddField(
            model_name='character',
            name='skill_expertise',
            field=models.CharField(default='', max_length=640),
        ),
        migrations.AddField(
            model_name='character',
            name='skill_proficiency',
            field=models.CharField(default='', max_length=640),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='bonus_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.characterstats'),
        ),
        migrations.AddField(
            model_name='characterspecies',
            name='bonus_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.characterstats'),
        ),
    ]
