# Generated by Django 4.2.7 on 2024-11-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_remove_characterclass_charisma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='skill_expertise',
            field=models.TextField(default='', max_length=640),
        ),
        migrations.AlterField(
            model_name='character',
            name='skill_proficiency',
            field=models.TextField(default='', max_length=640),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='skill_list',
            field=models.TextField(default='', max_length=640),
        ),
    ]
