# Generated by Django 4.2.7 on 2024-11-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_character_skill_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='modified_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
