# Generated by Django 4.2.7 on 2024-11-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_skill_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
