# Generated by Django 4.2.7 on 2024-12-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_alter_skill_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('bank_name', models.CharField(default='', max_length=100)),
                ('account_name', models.CharField(default='', max_length=100)),
                ('pp', models.IntegerField(blank=True, default=0, null=True)),
                ('po', models.IntegerField(blank=True, default=0, null=True)),
                ('pa', models.IntegerField(blank=True, default=0, null=True)),
                ('pc', models.IntegerField(blank=True, default=0, null=True)),
                ('pe', models.IntegerField(blank=True, default=0, null=True)),
                ('item', models.ManyToManyField(to='webapp.items')),
                ('owner', models.ManyToManyField(to='webapp.character')),
            ],
            bases=('webapp.guidmodel',),
        ),
    ]
