# Generated by Django 4.2.7 on 2025-01-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='skill_expertise',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skill_proficiency',
        ),
        migrations.AddField(
            model_name='characterstats',
            name='skill_expertise',
            field=models.TextField(default='', max_length=640),
        ),
        migrations.AddField(
            model_name='characterstats',
            name='skill_proficiency',
            field=models.TextField(default='', max_length=640),
        ),
    ]
