# Generated by Django 4.2.7 on 2025-01-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_remove_character_skill_expertise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='proficiency_bonus',
        ),
        migrations.AddField(
            model_name='characterstats',
            name='proficiency_bonus',
            field=models.IntegerField(default=2),
        ),
    ]
