# Generated by Django 4.2.7 on 2025-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_remove_character_proficiency_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterstats',
            name='skill_expertise',
            field=models.TextField(blank=True, default='', max_length=640, null=True),
        ),
        migrations.AlterField(
            model_name='characterstats',
            name='skill_proficiency',
            field=models.TextField(blank=True, default='', max_length=640, null=True),
        ),
    ]
