# Generated by Django 4.2.7 on 2025-01-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_alter_characterstats_skill_expertise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='pc',
            new_name='copper_coins',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='pe',
            new_name='electrum_coins',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='po',
            new_name='gold_coins',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='pp',
            new_name='platinum_coins',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='pa',
            new_name='silver_coins',
        ),
        migrations.RemoveField(
            model_name='character',
            name='copper_coins',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gold_coins',
        ),
        migrations.RemoveField(
            model_name='character',
            name='platinum_coins',
        ),
        migrations.RemoveField(
            model_name='character',
            name='silver_coins',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(default='Player', max_length=100),
        ),
    ]
