# Generated by Django 4.2.7 on 2025-01-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_rename_pc_bankaccount_copper_coins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='item',
            field=models.ManyToManyField(blank=True, to='webapp.items'),
        ),
    ]
