# Generated by Django 4.2.7 on 2025-01-15 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_alter_bankaccount_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterHealth',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('max_hp', models.IntegerField(blank=True, default=0, null=True)),
                ('current_hp', models.IntegerField(blank=True, default=0, null=True)),
                ('hp_dice', models.CharField(default='1d8', max_length=6)),
                ('temporary_hp', models.IntegerField(blank=True, default=0, null=True)),
                ('injury_threshold', models.IntegerField(blank=True, default=0, null=True)),
                ('temporary_corruption', models.IntegerField(blank=True, default=0, null=True)),
                ('permanent_corruption', models.IntegerField(blank=True, default=0, null=True)),
            ],
            bases=('webapp.guidmodel',),
        ),
    ]
