# Generated by Django 4.2.7 on 2025-01-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_characterhealth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='hp_dice',
        ),
        migrations.AddField(
            model_name='character',
            name='character_health',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.characterhealth'),
        ),
    ]
