# Generated by Django 4.2.7 on 2025-01-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_remove_characterclass_hp_dice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='class_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='characterhealth',
            name='hp_dice',
            field=models.CharField(blank=True, default='1d8', max_length=6, null=True),
        ),
    ]
