# Generated by Django 4.2.7 on 2025-03-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_characterclass_class_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.guidmodel')),
                ('item_name', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('is_homebrew', models.BooleanField(default=False)),
                ('character_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.character')),
            ],
            bases=('webapp.guidmodel',),
        ),
        migrations.RemoveField(
            model_name='characteritems',
            name='character_id',
        ),
        migrations.RemoveField(
            model_name='characteritems',
            name='guidmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='characteritems',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='characterweapon',
            name='character_id',
        ),
        migrations.RemoveField(
            model_name='characterweapon',
            name='guidmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='characterweapon',
            name='weapon_type',
        ),
        migrations.RemoveField(
            model_name='items',
            name='guidmodel_ptr',
        ),
        migrations.AddField(
            model_name='aptitude',
            name='character_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.character'),
        ),
        migrations.AddField(
            model_name='armor',
            name='character_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.character'),
        ),
        migrations.AddField(
            model_name='spell',
            name='character_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.character'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='character_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.character'),
        ),
        migrations.DeleteModel(
            name='characterArmor',
        ),
        migrations.DeleteModel(
            name='CharacterItems',
        ),
        migrations.DeleteModel(
            name='characterWeapon',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='item',
            field=models.ManyToManyField(blank=True, to='webapp.item'),
        ),
    ]
